SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_sportsmot.yaml

DATASETS: [AMFTracking]
DATASET_SPLITS: [train]

NUM_CLASSES: 1
MISS_TOLERANCE: 30
MAX_TRACKS: 0

DET_THRESH: 0.1
NEWBORN_THRESH: 0.5
ID_THRESH: 0.2

INFERENCE_DATASET: AMFTracking
INFERENCE_SPLIT: val
INFERENCE_MODE: submit
INFERENCE_DTYPE: FP16
INFERENCE_MAX_LONGER: 1536
