SUPER_CONFIG_PATH: ./configs/pretrain_r50_deformable_detr_sportsmot.yaml

EXP_NAME: amf_detr_pretrain

DATASETS: [AMFDetection]
DATASET_SPLITS: [train]

INFERENCE_DATASET:

EPOCHS: 20
LR: 1.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [15, ]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 2
ACCUMULATE_STEPS: 1

SAVE_CHECKPOINT_PER_EPOCH: 5
