SUPER_CONFIG_PATH: ./configs/rfdetr_motip_hockey_smoketest.yaml

SAMPLE_LENGTHS: [1, ]
DETR_NUM_TRAIN_FRAMES: 100
ONLY_DETR: True

EPOCHS: 20
LR: 1.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [15, ]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 2
ACCUMULATE_STEPS: 1
SAVE_CHECKPOINT_PER_EPOCH: 1
